# Generated by Django 4.2.30 on 2026-08-17 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('meeting_type', models.CharField(choices=[('sprint', 'Sprint Planning'), ('standup', 'Daily Standup'), ('client', 'Client Review'), ('one_on_one', '1-on-1 Sync'), ('retrospective', 'Retrospective'), ('board', 'Board / Executive'), ('general', 'General Meeting')], default='sprint', max_length=50)),
                ('participants', models.CharField(blank=True, help_text='Comma-separated participant names', max_length=500)),
                ('transcript', models.TextField(blank=True, help_text='Full meeting transcript or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('discussion_points', models.JSONField(blank=True, default=list)),
                ('key_decisions', models.JSONField(blank=True, default=list)),
                ('risks_and_concerns', models.JSONField(blank=True, default=list)),
                ('unanswered_questions', models.JSONField(blank=True, default=list)),
                ('raw_ai_response', models.JSONField(blank=True, default=dict)),
                ('ai_provider', models.CharField(default='mock', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='meetings.meeting')),
            ],
        ),
    ]
