# Generated by Django 4.2.30 on 2026-08-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('client_req', 'Client Requirement Discussion'), ('sprint', 'Sprint Planning'), ('standup', 'Daily Standup'), ('client', 'Client Review'), ('one_on_one', '1-on-1 Sync'), ('retrospective', 'Retrospective'), ('board', 'Board / Executive'), ('general', 'General Meeting')], default='sprint', max_length=50),
        ),
    ]
